### ISSUE TITLE
[bug]odin一键解包打包

### ISSUE THREAD

**Issue by TEACAET** [AiKirito/UY-Scuti#6]
不知道其他型号的情况，SM-X800的AP,CSC,HOME_CSC内有meta-data文件夹，其分别有fota.zip fota.zip download-list.txt,其中CSC的fota.zip为加密压缩包，看了眼目前的分类到Ready-to-flash的操作应该需要修改，同理到打包的那也需要修改。

在解压固件包的时候记录当前项目的AP,BL,CP,CSC,HOME_CSC的文件结构到文本中，之后根据记录放到Ready-to-flash的AP,BL,CP,CSC,HOME_CSC，应该不会影响hyperos那边的逻辑。同时对fota.zip缺少识别，我建议目前先不对其解压（ap下的文件很杂乱）直接放到对应包的Ready-to-flash路径。

SM-X800的参考文件结构：
[ap.txt](https://github.com/user-attachments/files/17175850/ap.txt)
[bl.txt](https://github.com/user-attachments/files/17175851/bl.txt)
[csc.txt](https://github.com/user-attachments/files/17175852/csc.txt)
[fota_ap.txt](https://github.com/user-attachments/files/17175853/fota_ap.txt)
[home_csc.txt](https://github.com/user-attachments/files/17175854/home_csc.txt)
[meta-data_home_csc.txt](https://github.com/user-attachments/files/17175855/meta-data_home_csc.txt)

ps：小提议就不开新issue了，一键打包能否考虑加入HOME_CSC，CSC是清除数据升级而HOME_CSC是保留数据升级

**Comment by BunnyYang05** [comment]
meta-data和fota.zip自己做官改都不用管的，CSC会清数据是因为里面的.pit文件，最终刷的包里没有pit就不会清除。

**Comment by TEACAET** [comment]
fota.zip原来是没用的，好吧
